# Netlify configuration for macsetup.asmat.dev
[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.sh"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Content-Disposition = "attachment"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/setup"
  to = "/mac-dev-setup.sh"
  status = 302

[[redirects]]
  from = "/install"
  to = "/"
  status = 301